config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
  #resourcesメソッドはルーティングを一括して自動生成してくれる
  #onlyは生成するルーティングを限定するオプション
  #不要なルーティングがされないようにonlyを設定する
    resource :favorites, only: [:create, :destroy]
   #resourceとなっているのは、単数にするとidがリクエストに含まれなくなるため
   #いいねの詳細ページは作成しないので、idの受け渡しも必要ないので、resourceとなっている
    resources:post_comments, only: [:create, :destroy]
    #コメントは投稿画像に対してコメントされる。→ post_commentsは、post_imagesに結びつく
    #このような親子関係を　ネストする　という
  end
  resources :users, only: [:show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post_image

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image

end

app/models/post_image.rb
class PostImage < ApplicationRecord

  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites,dependent: :destroy
  
  validates :shop_name, presence: true #ショップの名前が空かどうかの確認
  validates :image, presence: true #画像の投稿が空かどうかの確認


  def favorited_by?(user)#favorited_by?メソッド
    favorites.where(user_id: user.id).exists?#引数で渡されたユーザーidがFavoritesテーブル内に存在(exists?)してるかどうか調べている
  end

  attachment :image #_idは含めずに記述する
  #モデルに、画像アップ用のメソッド(attachment)を追加して、フィールド名に(image)を指定する
  #refileを使用する上でのルール
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image#_idは記述しない

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top]
  #ログイン認証が済んでいない状態でトップページ以外の画面にアクセスしても、ログイン画面へリダイレクトするように
  before_action :configure_permitted_parameters, if: :devise_controller?
  #deviseの利用機能(ユーザー登録、ログイン認証など)が使われる場合、
  #その前にconfigure_permitted_parametersが実行される
  def after_sign_in_path_for(resource)#ログイン後は投稿一覧画面に遷移するように設定
    post_images_path
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
   #devise_parameter_sanitizerでnameのデータを操作を許可するアクションメソッドが指定される
   #今回は、ユーザー登録(sign_up)の際に、ユーザー名(name)のデータ操作が行われる
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    post_image = PostImage.find(params[:post_image_id])#PostImageテーブルの投稿画像のidを見つけ、post_imageに代入
    favorite = current_user.favorites.new(post_image_id: post_image.id)#ログインしているユーザーが投稿画像にいいねをするということを、favoriteに代入する
    favorite.save#いいねを保存する
    redirect_to post_image_path(post_image)#いいねした投稿画像の詳細画面にリダイレクトする
  end

  def destroy
    post_image = PostImage.find(params[:post_image_id])#PostImageテーブルの投稿画像のidを見つけ、post_imageに代入
    favorite = current_user.favorites.find_by(post_image_id: post_image.id)#ログインしているユーザーが投稿画像にいいねされているのを見つけ、favoriteに代入する
    favorite.destroy#そのいいねを削除する
    redirect_to post_image_path(post_image)#いいねを消した投稿画像の詳細にリダイレクトする
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
#今回はコメント投稿だけの一覧画面や投稿画面は作成せず、
#その代わり、投稿画像の詳細画面(/post_image/:id)にコメント投稿機能を実装する
  def create
    post_image = PostImage.find(params[:post_image_id])#コメントする投稿内容を見つけてくる
    comment = current_user.post_comments.new(post_comment_params)#ログインしているユーザーが新規コメントをする
    comment.post_image_id = post_image.id#投稿画像のidをコメントに関連づける
    comment.save#保存する
    redirect_to post_image_path(post_image)#コメントした投稿画像の詳細画面にリダイレクトする

  end

  def destroy
    PostComment.find_by(id: params[:id]).destroy#find_by(id: params[:id])でコメントのidを探して削除する
    redirect_to post_image_path(params[:post_image_id])#削除したコメントの投稿画像にリダイレクトする

  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController

  def new
    @post_image = PostImage.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id #current_user.idでログインユーザーのidを取得することができる
    if @post_image.save
      redirect_to post_images_path
    else
      render :new
    end

  end

  def index
    @post_images = PostImage.page(params[:page]).reverse_order
    #pageメソッドはkaminariをインストールしたことで使えるようになったメソッド
    #reverse_oderは並び順を新しい投稿から古い投稿の順にする
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @psot_image.destroy
    redirect_to post_images_path
  end

  private

  def post_image_params
    params.require(:post_image).permit(:image, :shop_name, :caption)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])#userのidを取得することで関連づけられているそのユーザーの投稿(post_image)も取得できる
    @post_images = @user.post_images.page(params[:page]).reverse_order
    #そのユーザー(@user)に関連づけられた投稿(.post_images)のみ、@post_imagesに渡すことができる
  end

  def edit
    @user = User.find(params[:id])
    #params[:id]でユーザーの情報を取得してインスタンス(@user)に保存し、編集用Viewでform_withを使う準備をしている
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<h1>トップページ</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mesitero</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
      <!-- navbar・・・ナビゲーションバーの表示-->
      <!-- navbar-expand-[ブレークポイント]・・・指定したブレークポイント（画面幅）に応じてバーかアイコンを切り替えて表示 -->
      <!-- navbar-[カラースキーム]・・・ナビゲーションバーの色を指定する -->
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('logo.png') %></a>
          <!-- navbar-brand・・・ロゴに使用されるnavbarのサポートclass -->
          <!-- p-[サイズ]・・・paddingの指定 -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <!-- navbar-toggler・・・ナビゲーションアイコン（ハンバーガーメニュー）の枠部分の表示 -->
            <!-- navbar-toggler-icon・・・ナビゲーションアイコン（はンバーガーメニュー）の三本線 -->
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %> <!-- devise側で用意しているヘルパー -->
              <li class="nav-item">
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link text-dark" %>
                <!-- method: :deleteでdestroy_user_session_pathへルーティングさせ、ログアウト処理を行う -->
              </li>
              <li class="nav-item">
                <%= link_to '投稿フォーム',new_post_image_path, class: "nav-link text-dark" %>
              </li>
              <li class="nav-item">
                <%= link_to 'マイページ', user_path(current_user.id), class: "nav-link text-dark" %>
                <!-- 引数にcurrent_user.idを指定することで自分の詳細ページに飛ぶことができる-->
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to '新規登録', new_user_registration_path, class: "nav-link text-dark" %>
              </li>
              <li class="nav-item">
                <%= link_to 'ログイン', new_user_session_path, class: "nav-link text-dark" %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>善良な市民同士で無差別に食欲を煽るSNS</p>
            <%= image_tag('logo-white.png') %>
          </div>
          <div class="col-md-8">
            <h6 class="text-white mt-2 mb-3">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>
                <a href="" title="About" class="text-white-50">会社概要</a>
              </li>
              <li>
                <a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/post_images/_list.html.erb
<% post_images.each do |post_image| %>
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <%= link_to post_image_path(post_image.id) do %>
      <%= attachment_image_tag post_image, :image, class:"card-img-top"; %>
    <% end %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= attachment_image_tag post_image.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class:"mt-3 rounded-circle"; %>
        </div>
        <div class="col-10">
          <p class="card-title">
            <%= link_to(post_image_path(post_image.id), class:"text-dark") do %>
              <strong><i class="far fa-flag"></i><span> <%= post_image.shop_name %></span></strong>
            <% end %>
          </p>
          <p class="card-text">説明：<%= post_image.caption %></p>
          <span><i class="fas fa-user"></i> By <%= post_image.user.name %> ｜ </span>
          <span><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id), class:"text-dark" %></span>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <%= paginate post_images %>
</div>

app/views/post_images/index.html.erb
<%= render "post_images/list", post_images: @post_images %>

app/views/post_images/new.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">画像投稿フォーム</h5>
      <div class="form-body p-4">
        <% if @post_image.errors.any? %>
          <%= @post_image.errors.count %>件のエラーが発生しました
          <% @post_image.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <%= form_with model: @post_image, local:true do |f| %>
          <%= f.attachment_field :image, class: "w-100" %>
          <div class="input-group mb-3 mt-4">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-building"></i></span>
            </div>
            <%= f.text_field :shop_name, class:"form-control", placeholder:"ショップ名" %>
          </div>
          <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに" %>
          <hr>
          <%= f.submit '投稿', class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/post_images/show.html.erb
<div>
  <%= attachment_image_tag @post_image, :image %>
  <p>ショップ名:<%= @post_image.shop_name %></p>
  <p>説明:<%= @post_image.caption %></p>
  <p>ユーザーネーム:<%= @post_image.user.name %></p>
  <p>投稿日時:<%= @post_image.created_at.strftime('%Y%m%d') %></p>
  <!-- @post_image.created_at.strftime('%Y%m%d') 投稿日時の形式を変換しているメソッド-->
  <!-- '%Y%m%d' の記述で年/月/日へ変換している -->
  <% if @post_image.user == current_user %><!-- もし投稿者 == 現在ログインしているユーザーだったら -->
    <%= link_to "削除", post_image_path(@post_image), method: :delete %><!-- 削除する -->
  <% end %><!-- 終わり -->
</div>
<div>
  <p>コメント件数:<%= @post_image.post_comments.count %></p>
  <% @post_image.post_comments.each do |post_comment| %>
    <p><%= attachment_image_tag post_comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpeg" %></p>
    <%= post_comment.user.name %>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
    <% if post_comment.user == current_user %><!-- もしコメントしたユーザーだったら、削除ボタンを表示する -->
      <%= link_to "削除", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete %>
      <!-- ↑↑ コメントの削除なのでpost_comment#deleteのルートを確認して、pathまで記述し、（）の中に投稿詳細への引数を記述する -->
      <!-- ()の中が２つあるのは、ネストされているのでpost_comment.post_imageで投稿画像、post_commentでコメントをしていた投稿画像の先に飛ぶようにしている-->
    <% end %>
    <% if @post_image.favorited_by?(current_user) %>
    <!-- ↑↑ 投稿画像に付けられた「いいね」に自分（ログインしているユーザー)が含まれているかどうか -->
      <p>
        <%= link_to post_image_favorites_path(@post_image), method: :delete do %><!--　含まれている場合 -->
        ♥<%= @post_image.favorites.count %> いいね
        <% end %>
      </p>
      <% else %>
      <p>
        <%= link_to post_image_favorites_path(@post_image), method: :post do %><!-- 含まれていない場合 -->
        ♡<%= @post_image.favorites.count %> いいね
        <% end %>
      </p>
    <% end %>
  <% end %>
</div>

<div>
  <!-- コメントはpost_imageに結びついたpost_commentにあるため、２つ用意する必要がある -->
  <!-- post_commentをcreateするためのリクエストは、ルーティング -->
  <%= form_with(model:[@post_image,@post_comment],local: true) do |f| %>
    <%= f.text_area :comment, rows:'5', placeholder:"コメントをここに" %>
    <!-- rows:'5'　⇨　テキストエリアの高さを指定する　数字が多いほど高くなる -->
    <!-- 入力欄にあらかじめ記入されている薄い灰色のテキストのこと -->
    <%= f.submit "送信する" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model:@user,local:true do |f| %>
  <label for="inputName">Name</label><!-- <label>タグのfor属性の値と、フォーム部品のid属性の値を同じにすることで両者の関連付けができます。 -->
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前" %>
  <!--%= attachment_image_tag 保存先インスタンス名, :保存先カラム名, :サイズ（横幅,高さ）, 画像拡張子, 代替画像 % -->
  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
  <label for="inputImage">ProfileImage</label>
  <%= f.attachment_field :profile_image, placeholder:"プロフィール画像" %>
  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/show.html.erb
<!-- post_imagesのindex.html.erbファイルの内容をコピーして貼り付ける-->
<!-- users_controllerのshowでは@post_imagesを定義していないので定義する-->
<!-- ここから -->
<div>
  <h3><%= @user.name %></h3>
  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
  <% if @user.id == current_user %>
    <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
  <% end %>
</div>
<!-- ここまでコピーとは別に追加で記述する -->
<%= render "post_images/list", post_images: @post_images %>
<!-- render [部分テンプレートファイルの指定],[ローカル変数]:[渡す値]  -->